apiVersion: 1

datasources:
  - name: InfluxDB â€” opcua
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: true
    jsonData:
      version: Flux
      organization: opcua-demo
      defaultBucket: opcua
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-admin-token
